### ISSUE TITLE
Chapter 6 - where is cnn_utils

### ISSUE THREAD

**Issue by PCJimmmy** [dipanjanS/hands-on-transfer-learning-with-python#1]
Trying to follow along with the book - had an interest in CNN so I started with the CIFAR-10.  
This code finds no library
 - import cnn_utils as utils.  It's used at the end of the cifar10 transfer learning based classifier.  I cannot find it in my anaconda distribution - cant find it searching anaconda to add, and does not seem to be in the git for the book.
Where is it?

**Comment by dipanjanS** [comment]
@PCJimmmy  Thanks for pointing this out. I think this is a custom library\module so you may not find it in Anaconda. We will push the module to the repository soon

@raghavbali would be great if you could push the `cnn_utils.py` module and update here.

**Comment by PCJimmmy** [comment]
Thanks

Like the book – I bought a bunch over the last couple of months as I venture into Python – yours was my most recent purchase and finding it very helpful.

Jim

Sent from Mail for Windows 10

**Comment by raghavbali** [comment]
Updated repo with [```cnn_utils.py```](https://github.com/dipanjanS/hands-on-transfer-learning-with-python/blob/master/notebooks/Ch06%20-%20Image%20Recognition%20and%20Classification/cnn_utils.py)
Thanks for the catch @PCJimmmy , some how missed including the file. 

Kindly reopen if there are issues. Cheers!

**Comment by PCJimmmy** [comment]
Added a new issue about get_metrics from the same chapter and verse

– but the utils plot worked fine.

jim

Sent from Mail for Windows 10
