### ISSUE TITLE
get_metrics

### ISSUE THREAD

**Issue by PCJimmmy** [dipanjanS/hands-on-transfer-learning-with-python#2]
get_metrics - I had assumed that it would be in the missing cnn_utils - but now that file has been added and get_metrics not to be found.

DId a quick GitHub search - too many get_metrics - looked at first 15 pages of listings and did not see that tensorflow or keras had this.

I assume this line was the source for the 85% and 0.85 F1 score in the book.

**Comment by raghavbali** [comment]
@PCJimmmy ```get_metrics``` is being imported from ```model_evaluation_utils```.
This utility was introduced in chapter 5. I have added the same to chapter 6 as well for reference. Kindly pull the latest updates.

**Comment by PCJimmmy** [comment]
Ok – thanks

Guess I don’t know enough about GitHub yet to properly search – thought I looked thru it all for get_metrics

Jim

Sent from Mail for Windows 10

**Comment by raghavbali** [comment]
@PCJimmmy could we close the issue if the fix worked?

**Comment by PCJimmmy** [comment]
please close

**Comment by NguyenDangBinh** [comment]
training_data?
validation_data?
where are they? I did not know where are two files ?

**Comment by dipanjanS** [comment]
@NguyenDangBinh can you please open up a new issue with some more detail about which chapter, filename and code you are referencing, this will help us solve the issue better and faster.

**Comment by NguyenDangBinh** [comment]
Chapter 5
Basic CNN Model.ipynb
training_data and validation_data? where?

**Comment by dipanjanS** [comment]
@NguyenDangBinh: I think you would need follow the right order of steps to build the models. You need to first build the datasets before training and detailed steps are covered in [Datasets Builder.ipynb](https://github.com/dipanjanS/hands-on-transfer-learning-with-python/blob/master/notebooks/Ch05%20-%20Unleash%20the%20Power%20of%20Transfer%20Learning/Datasets%20Builder.ipynb).

Also would request to flag future issues in new issues and not on the already closed issues and that helps us easily find and solve new\open issues. Thanks!

**Comment by iconoclast007** [comment]
Where can I find the data files from Hands-on-TL?

**Comment by dipanjanS** [comment]
Please mention the exact specific data you are looking for and also the chapter name. Also this issue is a different issue which has been closed, so would request you to open a new issue with the specific details as needed.
